services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nsr
      POSTGRES_PASSWORD: nsr_dev
      POSTGRES_DB: nutristreetrun
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
