// NutriStreet Run — mock data (BR)
window.NSR_DATA = {
  user: {
    name: 'Rafael Mendes',
    initials: 'RM',
    city: 'São Paulo · SP',
    assessoria: 'Pace Livre Run Club',
    photoBg: 'linear-gradient(135deg,#F4620A 0%,#7a1a00 100%)',
    address: 'R. Aspicuelta, 412 — Vila Madalena, SP',
    plan: { name: 'NutriStreet Run', price: 'R$ 49,90/mês', nextCharge: '02 jun 2026', since: 'jan 2026' },
    stats: { totalMedals: 4, totalKm: 312.6, monthsActive: 5, bestRank: '#3 SP' },
  },
  challenge: {
    monthLabel: 'MAIO · 2026',
    title: 'DESAFIO 60K',
    subtitle: 'Corra 60 km até 31 de maio',
    goalKm: 60,
    doneKm: 38.4,
    daysLeft: 9,
    medalName: 'Medalha Maio · 60K',
  },
  recent: [
    { id: 1, title: 'Corrida matinal — Ibirapuera', date: 'hoje · 06:42', km: 8.2, pace: '5\'24"', counts: true, source: 'Strava' },
    { id: 2, title: 'Long run domingo', date: 'dom · 07:10', km: 14.1, pace: '5\'48"', counts: true, source: 'Strava' },
    { id: 3, title: 'Pedal pós-trabalho', date: 'sex · 19:02', km: 22.4, pace: '—', counts: false, reason: 'Ciclismo não conta', source: 'Strava' },
    { id: 4, title: 'Tiros 6×800m', date: 'qui · 06:30', km: 6.8, pace: '4\'58"', counts: true, source: 'Health' },
    { id: 5, title: 'Trote leve', date: 'ter · 06:15', km: 5.0, pace: '6\'02"', counts: true, source: 'Strava' },
    { id: 6, title: 'Caminhada parque', date: 'seg · 18:40', km: 3.1, pace: '8\'12"', counts: false, reason: 'Pace fora do critério', source: 'Health' },
  ],
  rankCity: [
    { pos: 1, name: 'Carolina Tavares', initials: 'CT', club: 'Avenida Run', km: 71.2 },
    { pos: 2, name: 'Bruno Saldanha', initials: 'BS', club: 'Iron Pace SP', km: 64.8 },
    { pos: 3, name: 'Rafael Mendes', initials: 'RM', club: 'Pace Livre Run Club', km: 38.4, isMe: true },
    { pos: 4, name: 'Mariana Okabe', initials: 'MO', club: 'Pace Livre Run Club', km: 36.5 },
    { pos: 5, name: 'Thiago Albuquerque', initials: 'TA', club: 'NorteSul Runners', km: 35.1 },
    { pos: 6, name: 'Letícia Vasconcelos', initials: 'LV', club: 'Avenida Run', km: 32.7 },
    { pos: 7, name: 'Gabriel Pacheco', initials: 'GP', club: 'Iron Pace SP', km: 31.0 },
  ],
  rankState: [
    { pos: 1, name: 'Felipe Camargo', initials: 'FC', club: 'Litoral Run Campinas', km: 88.0 },
    { pos: 2, name: 'Carolina Tavares', initials: 'CT', club: 'Avenida Run', km: 71.2 },
    { pos: 3, name: 'Júlia Bertolucci', initials: 'JB', club: 'Santos On Track', km: 67.4 },
    { pos: 4, name: 'Bruno Saldanha', initials: 'BS', club: 'Iron Pace SP', km: 64.8 },
    { pos: 5, name: 'Rafael Mendes', initials: 'RM', club: 'Pace Livre Run Club', km: 38.4, isMe: true },
    { pos: 6, name: 'Diego Nakamura', initials: 'DN', club: 'Ribeirão Sub-5', km: 38.0 },
  ],
  rankClubs: [
    { pos: 1, name: 'Avenida Run', city: 'São Paulo · SP', runners: 142, km: 4820 },
    { pos: 2, name: 'Iron Pace SP', city: 'São Paulo · SP', runners: 98, km: 3611 },
    { pos: 3, name: 'Pace Livre Run Club', city: 'São Paulo · SP', runners: 64, km: 2104, isMe: true },
    { pos: 4, name: 'Litoral Run Campinas', city: 'Campinas · SP', runners: 71, km: 1988 },
    { pos: 5, name: 'NorteSul Runners', city: 'Guarulhos · SP', runners: 45, km: 1402 },
    { pos: 6, name: 'Santos On Track', city: 'Santos · SP', runners: 38, km: 1190 },
  ],
  medals: [
    { id: 1, label: 'Maio · 60K', month: 'mai/26', status: 'progress', goal: 60, done: 38.4 },
    { id: 2, label: 'Abril · 50K', month: 'abr/26', status: 'shipped', tracking: 'BR998213721SP' },
    { id: 3, label: 'Março · 50K', month: 'mar/26', status: 'delivered' },
    { id: 4, label: 'Fevereiro · 40K', month: 'fev/26', status: 'delivered' },
    { id: 5, label: 'Janeiro · 40K', month: 'jan/26', status: 'delivered' },
    { id: 6, label: 'Dezembro · 50K', month: 'dez/25', status: 'missed' },
  ],
  benefits: [
    { t: 'Desafio mensal', d: 'Meta de km que cresce com você. Cumpriu, ganhou medalha.' },
    { t: 'Medalha física em casa', d: 'Cumpriu a meta? A medalha do mês é enviada pro endereço cadastrado, sem custo extra.' },
    { t: 'Ranking real', d: 'Compita por cidade, estado e assessoria. Ranking atualiza em tempo real.' },
    { t: 'Sync automático', d: 'Strava + Apple Health + Google Fit. Você corre, a gente conta.' },
    { t: 'Feed da comunidade', d: 'Veja o que sua assessoria e seus pares estão fazendo.' },
    { t: 'Conteúdo NutriSilva', d: 'Acesso ao ecossistema do nutricionista esportivo Dr. Silva.' },
  ],
};
